feature/MARP-278-Artifact-selector-must-display-unique-option
axonivy-market/market.axonivy.com pull request #45
Opened 2024-05-22 10:06 UTC by nntthuy-axonivy

2024-05-23 09:19 UTC, tutn-axonivy commented on src/app/pages/product/ProductView.php
> +    return array_filter($mavenArtifacts, fn (MavenArtifact $artifact) => $artifact->getMakesSenseAsMavenDependency());
remove the space after fn

2024-05-23 09:56 UTC, tutn-axonivy approved these changes
LGTM

2024-05-23 10:12 UTC, nntthuy-axonivy commented
Hi @alexsuter, currently artifact dropdown has duplicated names because name in meta.json and product.json are the same. To prevent this issue, I filter list of artifacts based on their name and type before rendering them in UI.
Please have a look on this PR. Thank you!

2024-05-27 06:33 UTC, alexsuter commented
Please add a test.

2024-05-27 07:23 UTC, alexsuter reviewed
Please add a test

2024-05-28 14:04 UTC, alexsuter commented
Can you show me in the axon ivy market which one has duplicated artifacts at the moment?

2024-05-28 14:46 UTC, nntthuy-axonivy commented
> Can you show me in the axon ivy market which one has duplicated artifacts at the moment?

Hi @alexsuter, "Adobe Acrobat Connector" has 3 duplicated artifact names
![image](https://github.com/axonivy-market/market.axonivy.com/assets/145430420/c12e5360-6bb0-4731-bbf0-dae852f8781d)
I haven't finished writing tests, just committed new codes to check CI build. I'll inform you when PR is ready to review.

2024-05-28 14:53 UTC, alexsuter commented
I think this was not the case before you have merged some other PRs. What's the reason why this happen now?

2024-05-28 14:58 UTC, nntthuy-axonivy commented
> I think this was not the case before you have merged some other PRs. What's the reason why this happen now?

oh I do not notice that it was correct before. Let me check which PR affects this case

2024-05-29 08:59 UTC, nntthuy-axonivy commented
Hi @alexsuter, I discovered that some PRs are affecting the code. My proposed solution for Adobe Acrobat Connector is to remove the "archiveArtifacts" block in meta.json, add a "-demo" suffix to the `artifactId` in `maven-import`, and then close the PR. What are your thoughts?

2024-05-29 11:54 UTC, alexsuter requested changes
I think this PR solves an issue which has been introduced before. Therefore I would fix the real problem. Rather than implementing new hacks.

2024-06-05 11:54 UTC, alexsuter commented
Closing this PR and rename the branch to stale/* to have less builds on our build server.

2024-06-05 11:54 UTC, closed without merging